apiVersion: v1
kind: Namespace
metadata:
  name: routing-experiment
  labels:
    name: routing-experiment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: routing-experiment
  labels:
    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: go-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: routing-experiment
  labels:
    app: go-app
spec:
  selector:
    app: go-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP